version: "3.1"
services:
  nginx:
    image: nginx:alpine
    container_name: daily-news-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public_html/daily-news-bot/:/var/www
    depends_on:
      - php
    networks:
      - daily-bot-net
  php:
    build: ./dockerfiles/php
    container_name: daily-news-php
    restart: always
    volumes:
      - ./public_html/daily-news-bot/:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    environment:
      PHP_IDE_CONFIG: serverName=dima
    networks:
      - daily-bot-net
  mysql:
    image: mysql:5.7
    container_name: daily-news-database
    restart: always
    ports:
      - "3320:3306"
    env_file:
      - .env
    volumes:
      - ./var/mysql/data:/var/lib/mysql
    networks:
      - daily-bot-net
  redis:
    image: redis:alpine
    container_name: daily-news-redis-storage
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./var/redis-data:/data
    ports:
     - "6379:6379"
    networks:
      - daily-bot-net
networks:
  daily-bot-net:
    driver: bridge
